# Generated by Django 4.2.7 on 2023-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("card_number", models.CharField(max_length=16)),
                ("expiration_date", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
