# Generated by Django 4.2.7 on 2023-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-req_count",)},
        ),
        migrations.AddField(
            model_name="user",
            name="req_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("blocked", "Blocked"), ("unblock", "Unblock")],
                default="unblock",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unblock_time",
            field=models.DateTimeField(null=True),
        ),
    ]
